### ISSUE TITLE
readme - repo trebuie actualizat

### ISSUE THREAD

**Issue by andreiepure** [mgax/dexonline-vagrant#1]
-    git clone git://github.com/alex-morega/dexonline-vagrant.git vagrant
-    git clone git://github.com/mgax/dexonline-vagrant.git vagrant

Cum pot obține permisiunea să fac commit?

remote: Permission to mgax/dexonline-vagrant.git denied to andreiepure.
fatal: unable to access 'https://github.com/mgax/dexonline-vagrant.git/': The requested URL returned error: 403

**Comment by mgax** [comment]
@andreiepure, nu poți să faci push direct în repository, dar poți să faci un [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by revolter** [comment]
Nu era mai rapid sa faci tu un edit direct?

**Comment by andreiepure** [comment]
@revolter : scuze, o lăsasem baltă atunci, m-am apucat să scriu instrucțiuni folosing ScotchBox, care e întreținut la zi. Dacă mergi pe calea mașinii virtuale, te rog să setezi o mașină cu ScotchBox ca [pe wiki ](https://github.com/dexonline/dexonline/wiki/Instruc%C8%9Biuni-de-instalare-ma%C8%99in%C4%83-virtual%C4%83) și să îmbunătățești ce nu merge, ultima oară când am reluat lucrul la instrucțiuni, tot mai era de îmbunătățit. ScotchBox e întreținut la zi. Mulțumesc.

**Comment by revolter** [comment]
@andreiepure, Ulterior am observat ca e vechi repository-ul asta, scuze.
